name: Actions Workflow


on: 
  schedule:
    - cron: '* * * * *'
  push:

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files After Checkout
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token}}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple Javascript Actions
        uses: actions/hello-world-javascript-action@v1.1
        id: greet
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}" 