name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
  run-other-shell-command:
    runs-on: macos-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
          if command -v brew > /dev/null 2>&1, then: echo "brew is installed" brew -v brew list else echo "brew isn't installed"; fi 
